### PR TITLE
[11.0][IMP] mdc: input data cancel mode

### PR DESCRIPTION
**Pull request by dalonsod**
Selects how the input cancel cron will be perform the old unlinked inputs expiration:
- 1-day old (default): when an input is 24 hours old or more
- yesterday: when an input belongs to a previous day than today

Not tested yet

### CODE REVIEW

**Comment by dalonsod** [comment]
@lmiguens-solvos tested, the following issue is faced:

- available dates in python processes take in account timezone. For example, an input created at 17:30, actually 15:30 is filled (because today we're in UTC+2)
- but, if we need an absolute reference (i.e. the start or end of the day), if we take `datetime.now()` (with the same behavior of UTC+2) and set to e.g. 00:00:00 and use it... then we shoud actually comparing dates UTC, thus we've comparing with 02:00 hours in Spain (or 01:00 in winter)!

For our case, the inputs for "yesterday" mode will be effectively cancelled at that hours, 1 or 2 later than expected. Is it enough for us, or should I study get the current timezone and try to apply it?

**Comment by lmiguens-solvos** [comment]
> @lmiguens-solvos tested, the following issue is faced:
> 
> * available dates in python processes take in account timezone. For example, an input created at 17:30, actually 15:30 is filled (because today we're in UTC+2)
> * but, if we need an absolute reference (i.e. the start or end of the day), if we take `datetime.now()` (with the same behavior of UTC+2) and set to e.g. 00:00:00 and use it... then we shoud actually comparing dates UTC, thus we've comparing with 02:00 hours in Spain (or 01:00 in winter)!
> 
> For our case, the inputs for "yesterday" mode will be effectively cancelled at that hours, 1 or 2 later than expected. Is it enough for us, or should I study get the current timezone and try to apply it?

I tested this improvement and it works.

Regarding the time of execution, at first I thought it didn't matter much that they were canceled at 2 in the morning instead of at 00:05 ...
But right in the database of Santoña I found data of tickets at 10 p.m. (on 04/15 ...) and those tickets, with our process we would end up canceling them ...
Surely it was something occasional, but I don't know ...
Perhaps Luis would have to help us decide, since he knows the work on site better.

**Comment by dalonsod** [comment]
@lmiguens-solvos you're right. I'll take a look

**Comment by dalonsod** [comment]
@lmiguens-solvos added `i18n` updates. I'll merge it ASAP, but GitHub is experiencing problems...

Commit message will remember us the know issue with "yesterday" mode:

imagen

**Comment by dalonsod** [comment]
> Commit message will remember us the know issue with "yesterday" mode:
> 
> imagen

Grrrrr.... https://github.com/odoo/odoo/blob/11.0/odoo/fields.py#L1525

imagen

If "yesterday" mode is finally used, we should try this :(

**Comment by lmiguens-solvos** [comment]
> > Commit message will remember us the know issue with "yesterday" mode:
> > imagen
> 
> Grrrrr.... https://github.com/odoo/odoo/blob/11.0/odoo/fields.py#L1525
> 
> imagen
> 
> If "yesterday" mode is finally used, we should try this :(

Well, it really would be very interesting to try it.

**Pull request merged**
